version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nik-laravel-backend
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8082:8000" #8082 is post of real machine, 8000 is the posrt where NGNIX lisning
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #Cache Service
  redis:
    image: redis:alpine
    container_name: myapp-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass 12344321
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - app-network
  #Search Service
  elasticsearch:
    container_name: es-container
    restart: unless-stopped
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - app-network
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    restart: unless-stopped
    image: docker.elastic.co/kibana/kibana:8.6.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - app-network
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
